import Foundation

/// Clipboard history settings in the input method's defaults domain, read on every use.
struct ClipboardSettings: Equatable {
    static let enabledKey = "ClipboardHistoryEnabled"
    static let hotkeyKey = "ClipboardHistoryHotkey"
    static let retentionKey = "ClipboardHistoryRetentionDays"
    static let imagesKey = "ClipboardHistoryImages"
    /// ⌃⌥V (V is ANSI key code 9): open the history.
    static let defaultHotkey = TranslationHotkey(keyCode: 9, modifiers: [.control, .option])
    static let retentionChoices = [1, 7, 30, 90]
    static let defaultRetentionDays = 30

    /// Password managers: what they put on the clipboard is a secret, so it is never kept. Terminals are
    /// kept, since commands are among the things worth finding again.
    static let excludedApps: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
    ]

    /// Pasteboard types that mark a copy as a secret or as machine-made (nspasteboard.org).
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    let isEnabled: Bool
    let hotkey: TranslationHotkey
    let retentionDays: Int
    let keepsImages: Bool

    init(defaults: UserDefaults = .standard) {
        isEnabled = defaults.object(forKey: Self.enabledKey) as? Bool ?? true
        hotkey = defaults.string(forKey: Self.hotkeyKey).flatMap(TranslationHotkey.init(string:)) ?? Self.defaultHotkey
        let days = defaults.integer(forKey: Self.retentionKey)
        retentionDays = days > 0 ? days : Self.defaultRetentionDays
        keepsImages = defaults.object(forKey: Self.imagesKey) as? Bool ?? true
    }

    static func setEnabled(_ enabled: Bool, defaults: UserDefaults = .standard) {
        defaults.set(enabled, forKey: enabledKey)
    }

    static func setRetentionDays(_ days: Int, defaults: UserDefaults = .standard) {
        defaults.set(days, forKey: retentionKey)
    }

    static func setKeepsImages(_ keeps: Bool, defaults: UserDefaults = .standard) {
        defaults.set(keeps, forKey: imagesKey)
    }

    /// Whether a copy made in `app` with these pasteboard types may be recorded.
    static func allowsCopy(from app: String?, types: [String]) -> Bool {
        if let app, excludedApps.contains(app) {
            return false
        }
        return ignoredTypes.isDisjoint(with: types)
    }
}
